name: nginx

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../backend/src/internal/router/dashboard/static/dist:/app
    env_file:
      - .env

