/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MaterialSymbolsAdd2Rounded: typeof import('~icons/material-symbols/add2-rounded')['default']
    MaterialSymbolsArrowBack: typeof import('~icons/material-symbols/arrow-back')['default']
    MaterialSymbolsArrowBackIosNewRounded: typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
    MaterialSymbolsArrowForwardIosRounded: typeof import('~icons/material-symbols/arrow-forward-ios-rounded')['default']
    MaterialSymbolsCheckRounded: typeof import('~icons/material-symbols/check-rounded')['default']
    MaterialSymbolsContentCopyOutlineRounded: typeof import('~icons/material-symbols/content-copy-outline-rounded')['default']
    MaterialSymbolsDeleteOutlineRounded: typeof import('~icons/material-symbols/delete-outline-rounded')['default']
    MaterialSymbolsEditSquareOutlineRounded: typeof import('~icons/material-symbols/edit-square-outline-rounded')['default']
    MaterialSymbolsListsRounded: typeof import('~icons/material-symbols/lists-rounded')['default']
    MaterialSymbolsLogoutRounded: typeof import('~icons/material-symbols/logout-rounded')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
